//
// Created by Karsten Belt on 19/12/2022.
//

#ifndef PLATFORMER_GAME_DYNAMICANIMATIONBEHAVIOUR_H
#define PLATFORMER_GAME_DYNAMICANIMATIONBEHAVIOUR_H

#endif //PLATFORMER_GAME_DYNAMICANIMATIONBEHAVIOUR_H
