name: 'Build'

on:
  pull_request:

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            triplet: x64-linux
          - os: self-hosted-macos-m1 
            triplet: arm64-osx
          # - os: self-hosted-linux-arm64
          #   triplet: arm64-linux
          - os: self-hosted-linux-x64
            triplet: x64-linux

    env:
      VCPKG_DEFAULT_TRIPLET: ${{ matrix.triplet }}

    steps:
      - name: 'Install SDL2 dev'
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libsdl2-dev
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          submodules: recursive

      - name: 'Install CMake'
        uses: lukka/get-cmake@latest

      - name: 'Setup vcpkg'
        uses: lukka/run-vcpkg@v10

      - name: 'Run CMake'
        uses: lukka/run-cmake@v10
        with:
          configurePreset: ninja-multi-vcpkg
          buildPreset: ninja-multi-vcpkg