name: 'Doxygen'

on:
 push:
   branches:
     - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          submodules: recursive

      - name: 'Generate Doxygen documentation'
        uses: mattnotmitt/doxygen-action@v1.3.1

      - name: 'Push to docs repo'
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PAT }}
          publish_dir: html
          external_repository: SPC-H-Avans/game-docs
          publish_branch: main
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_message: ${{ github.sha }}
          cname: game.mrproper.dev