name: 'Publish'

on:
  pull_request:
#  push:
#    branches:
#      - main

jobs:
  build:
    name: Build (${{ matrix.name }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            name: Windows
            triplet: x64-windows-static
          - os: ubuntu-latest
            name: Linux
            triplet: x64-linux

    env:
      VCPKG_DEFAULT_TRIPLET: ${{ matrix.triplet }}

    steps:
      - name: 'Install SDL2 dev'
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libsdl2-dev
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          submodules: recursive

      - name: 'Install CMake'
        uses: lukka/get-cmake@latest

      - name: 'Setup vcpkg'
        uses: lukka/run-vcpkg@v10

      - name: 'Run CMake'
        uses: lukka/run-cmake@v10
        with:
          configurePreset: ninja-multi-vcpkg
          buildPreset: ninja-multi-vcpkg

      - name: 'Upload build'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.name }}
          path: builds/ninja-multi-vcpkg/Release/

  publish:
    name: 'Publish'
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: 'Download builds'
        uses: actions/download-artifact@v2
        with:
          path: build

      - name: 'Push to builds repo'
        uses: cpina/github-action-push-to-another-repository@v1.3
        env:
          API_TOKEN_GITHUB: ${{ secrets.PAT }}
        with:
          source-directory: build
          destination-github-username: SPC-H-Avans
          destination-repository-name: game-builds
          user-email: 41898282+github-actions[bot]@users.noreply.github.com
          target-branch: main
          commit-message: ${{ github.sha }}

      - name: 'Delete builds'
        uses: geekyeggo/delete-artifact@v1
        with:
          name: |
            Windows
            Linux
          failOnError: false