name: 'Publish'

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build (${{ matrix.name }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            name: Windows
            triplet: x64-windows-static
          - os: ubuntu-latest
            name: Linux
            triplet: x64-linux

    env:
      VCPKG_DEFAULT_TRIPLET: ${{ matrix.triplet }}

    steps:
      - name: 'Install SDL2 dev'
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libsdl2-dev
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          submodules: recursive

      - name: 'Install CMake'
        uses: lukka/get-cmake@latest

      - name: 'Setup vcpkg'
        uses: lukka/run-vcpkg@v10

      - name: 'Run CMake'
        uses: lukka/run-cmake@v10
        with:
          configurePreset: ninja-multi-vcpkg
          buildPreset: ninja-multi-vcpkg

      - name: 'Upload build'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.name }}
          path: builds/ninja-multi-vcpkg/Release/

  changelog:
    name: 'Get the changelog'
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
    
      # - name: 'Get the changelog'
      #   id: changelog
      #   uses: mikepenz/release-changelog-builder-action@v3
      #   with:
      #     token: ${{ secrets.PAT }}

      # - name: 'Print the changelog'
      #   run: echo "${{ steps.changelog.outputs.changelog }}"

      # - name: 'Save to markdown file'
      #   run: echo "${{ steps.changelog.outputs.changelog }}" > changelog.md

      - name: 'Upload the changelog'
        uses: actions/upload-artifact@v2
        with:
          name: changelog
          path: CHANGELOG.md

  publish:
    name: 'Publish'
    runs-on: ubuntu-latest
    needs: changelog

    steps:
      - name: 'Download builds'
        uses: actions/download-artifact@v2
        with:
          path: build

      - name: 'Download changelog'
        uses: actions/download-artifact@v2
        with:
          name: changelog
          path: changelog

      - name: 'Zip builds'
        run: |
          cd build
          ls -l
          zip -r linux.zip Linux
          zip -r windows.zip Windows
          cd ../

      - name: 'Push to builds repo'
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.PAT }}
        with:
          source-directory: build
          destination-github-username: SPC-H-Avans
          destination-repository-name: game-builds
          user-email: 41898282+github-actions[bot]@users.noreply.github.com
          target-branch: main
          commit-message: ${{ github.sha }}

      - name: 'Create new release'
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/linux.zip,build/windows.zip"
          tag: ${{ github.ref }}
          name: ${{ github.ref }}
          bodyFile: changelog/CHANGELOG.md
          owner: SPC-H-Avans
          repo: game-builds
          token: ${{ secrets.PAT }}

      - name: 'Delete builds'
        uses: geekyeggo/delete-artifact@v1
        with:
          name: |
            Windows
            Linux
          failOnError: false

      - name: 'Delete changelog'
        uses: geekyeggo/delete-artifact@v1
        with:
          name: changelog
          failOnError: false